### ISSUE TITLE
unlock manually in linux

### ISSUE THREAD

**Issue by rho-sk** [ChubbyAnt/sedutil#29]
How is it possible to achieve functionality of manual unlock "data disk" by user after linux is up& running. 
Is it possible with sedutil ?
And after poweroff, i expect that disk is locked again.
Thanks

**Comment by ChubbyAnt** [comment]
To unlock manually within Linux just use the sedutil-cli binary in releases, or compile your own binary from source.

**Comment by dalaeance** [comment]
@ChubbyAnt, I have a somewhat related question. 

Since the wiki article doesn't address how you'd lock additional drives (non-boot drives), would I simply repeat the instructions in the "[Enable locking and the PBA](https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive#enable-locking-and-the-pba)" section? If so, I imagine I'd simply skip unzipping & loading the PBA for the additional drives?

**Comment by tigaente** [comment]
Try `sedutil-cli --setLockingRange 0 rw <password> <device>` to manually unlock a drive.
You can also checkout https://github.com/dex6/sed-opal-unlocker for this purpose.

For non-boot drives, locking is enough. You can skip the PBA part.

**Comment by dalaeance** [comment]
Thanks, @tigaente
