### ISSUE TITLE
Build Error with glibc > 2.28

### ISSUE THREAD

**Issue by mabachel** [ChubbyAnt/sedutil#7]
Hey,
following your Build instructions I encountered build errors because I use Feodora 30 which ships with glibc-2.29 instead of glibc-2.27 of your Ubuntu 18.04 LTS.

The problem is not in sedutil itself but rather in GNU's M4.

I reported the bug here

https://lists.gnu.org/archive/html/bug-m4/2019-10/msg00000.html

but it seems the bug has already been reported months ago with no new update although a bug fix seems rather trivial.

In any case I wanted to let you know because you will probably encounter the bug itself at latest after an upgrade to Ubuntu 20.04 LTS.

Best regards

**Comment by ChubbyAnt** [comment]
Thank you. This is a known issue.

**Comment by mabachel** [comment]
Yes I know. I referenced to the exact same gnulib repo for the fix in my mail to bug-m4 list.

But it seems there is no reason to believe it will get fixed any time soon. Sadly I struggle fixing it on my own since some build script downloads the source and builds it but I don't know where. One could add a "run patch" line in the build script after download and extraction of the source.

Can anyone help? My knowledge is not sufficient..

**Comment by oom-is** [comment]
Please take a look at the the pull request ([#306](https://github.com/Drive-Trust-Alliance/sedutil/pull/306)) I submitted against the vanilla DTA sedutil.  It updates the buildroot target to 2019.02.6 (latest LTS buildroot2) and the Linux kernel to 4.14.146 (latest kernel in that 4.14 LTS series) and should apply cleanly against any tree that doesn't otherwise touch buildroot .config or kernel.config "stuff" below the images/buildroot directory.

I don't know for sure whether this will fix your errors, but since the older Buildroot 2017.x targets are no longer formally supported, there's a much better chance that Things Will Just Work with the newer buildroot target.  Please let me know of any feedback.

Side note for ChubbyAnt if you read this - I didn't specifically go back and test the images from your tree, but from my current [integration tree](https://github.com/oom-is/sedutil/tree/integ) at least (which includes the LTS pull request above) I do not need to enable CSM to boot on a 64-bit UEFI system.  YMMV but it may be helpful to document that feature if it works for you, since some newer PCs are starting to show up that no longer support CSM for boot off internal UEFI devices.

**Comment by ChubbyAnt** [comment]
@oom-is your commit #306 has been merged into this repo. Awesome work!

**Comment by mabachel** [comment]
Awesome! I can successfully build now.
This issue can be closed.
